# -*- coding: utf-8 -*-
"""Untitled40.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZPpGcn9lb8yttcPQJOIwXTHpit2WPsfA
"""

import rasterio
import numpy as np
import glob
from scipy.ndimage import median_filter
from scipy.ndimage import generic_filter
import os # Import the os module
import geopandas as gpd # Import geopandas for vector operations
from rasterio.features import shapes # Import shapes for polygonization

output_dir = '/gdrive/MyDrive/COV/Classified/'  # Define your output directory
os.makedirs(output_dir, exist_ok=True)

# Define the directory containing the raster files
raster_dir = '/gdrive/MyDrive/COV/'

# Use glob to find all raster files in the directory
raster_files = glob.glob(raster_dir + '*.tif')  # Adjust file extension if needed

def nanmedian_filter(data, size):
    return generic_filter(data, np.nanmedian, size=size)


for file in raster_files:
    with rasterio.open(file) as src:
        data = src.read(1)  # Read the first band
        #filtered_data = nanmedian_filter(data, size=3)    # Apply median filter to individual raster
        data = np.ma.masked_invalid(data)
        # Calculate percentiles for classification # This should be inside the loop to calculate percentiles for each file
        percentiles = np.nanpercentile(data, [30, 70, 100])
        classified_data = np.zeros_like(data, dtype=int)
        classified_data[data <= percentiles[0]] = 1  # Class 1: values below 30th percentile
        classified_data[(data > percentiles[0]) & (data <= percentiles[1])] = 2  # Class 2: values between 30th and 70th percentile
        classified_data[(data > percentiles[1]) & (data <= percentiles[2])] = 3  # Class 3: values between 70th and 100th percentile
        classified_data[data > percentiles[2]] = 4  # Class 4: values above 75th percentile

        # Construct output file name - this was incorrectly indented
        file_name, file_ext = os.path.splitext(os.path.basename(file))

        # Assuming band_index is 1 since you are reading band 1
        output_file = os.path.join(output_dir, f"{file_name}_classified{file_ext}")

        # Save the classified data to a separate file
        with rasterio.open(
            output_file,
            'w',
            driver='GTiff',
            height=classified_data.shape[0],
            width=classified_data.shape[1],
            count=1,
            dtype=classified_data.dtype,
            crs=src.crs,
            transform=src.transform,
        ) as dst:
            dst.write(classified_data, 1)  # Write the classified data

            # ---------------------------------

        # Extract shapes from the classified raster
        classified_data = classified_data.astype(rasterio.uint8)
        results = (
            {'properties': {'raster_val': v}, 'geometry': s}
            for i, (s, v)
            in enumerate(
                shapes(classified_data, transform=src.transform)))

        # Create a GeoDataFrame from the extracted shapes
        geodf = gpd.GeoDataFrame.from_features(list(results), crs=src.crs)

        # Construct output file name for the vector data (Shapefile)
        # Change: Use file from the loop, instead of file_name from previous cell.
        file_name, file_ext = os.path.splitext(os.path.basename(file))
        vector_file = os.path.join(output_dir, f"{file_name}_classified.shp")

        # Save the GeoDataFrame to a Shapefile
        geodf.to_file(vector_file, driver='ESRI Shapefile')