# -*- coding: utf-8 -*-
"""TM_ClassifRF.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gt4Jm_YkJ0oG9n5P7ViLLUNqNrCKrHpj
"""

from google.colab import drive
drive.mount('/gdrive')

!pip install rasterio


import pandas as pd
import rasterio
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap # Import ListedColormap
import seaborn as sns
from rasterio.warp import reproject, Resampling
from sklearn.ensemble import RandomForestRegressor
from sklearn.inspection import permutation_importance
from sklearn.metrics import confusion_matrix, cohen_kappa_score, classification_report
from scipy.ndimage import median_filter
from sklearn.model_selection import train_test_split
# =====================
# 1. Rasters multibandes
# =====================
raster_paths = {
    "NDVI": "/gdrive/MyDrive/HML/NDVI_Med_Pluriann.tif",
    "NDWI": "/gdrive/MyDrive/HML/Pluriann_NDWI/NDWI_Med_Pluriann.tif",
    "TPI":  "/gdrive/MyDrive/HML/TPI_10m.tif",
    "SSM":  "/gdrive/MyDrive/HML/SSM_Med_Pluriann.tif",
    "TWI":  "/gdrive/MyDrive/HML/TWI_10m.tif"
}
# === 2. Raster de référence (NDVI comme Y) ===
ref_path = raster_paths["NDVI"]
with rasterio.open(ref_path) as ref:
    ref_profile = ref.profile
    ref_shape = ref.shape
    ref_transform = ref.transform
    ref_crs = ref.crs
    y_full = ref.read(1).astype(np.float32).flatten()  # NDVI cible

# === 3. Aligner les autres rasters sur NDVI ===
aligned_arrays = []
for var, path in raster_paths.items():
    if var == "NDVI":  # NDVI est Y
        continue
    with rasterio.open(path) as src:
        data = src.read(1)

        aligned = np.empty(ref_shape, dtype=np.float32)

        reproject(
            source=data,
            destination=aligned,
            src_transform=src.transform,
            src_crs=src.crs,
            dst_transform=ref_transform,
            dst_crs=ref_crs,
            resampling=Resampling.nearest
        )
        aligned_arrays.append(aligned.flatten())

# === 4. Construire X et Y ===
X = np.vstack(aligned_arrays).T
mask = np.all(~np.isnan(X), axis=1) & ~np.isnan(y_full)
X = X[mask, :]
y = y_full[mask]

# === 5. Split train/test ===
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.3, random_state=42
)

# === 6. Random Forest Regression ===
rf = RandomForestRegressor(n_estimators=100, random_state=42, n_jobs=-1)
rf.fit(X_train, y_train)

print("R² train :", rf.score(X_train, y_train))
print("R² test  :", rf.score(X_test, y_test))

# === 7. Importances ===
feature_names = [k for k in raster_paths.keys() if k != "NDVI"]

# IncNodePurity
inc_node_purity = rf.feature_importances_

# %IncMSE
perm = permutation_importance(
    rf, X_test, y_test, n_repeats=20, random_state=42, n_jobs=-1
)

importance_df = pd.DataFrame({
    "Variable": feature_names,
    "IncNodePurity": inc_node_purity,
    "%IncMSE": perm.importances_mean
}).sort_values("%IncMSE", ascending=True)

print("\n=== Importances des variables ===")
print(importance_df)

# === 8. Graphiques comparatifs ===
fig, axes = plt.subplots(1, 2, figsize=(12,6))

# %IncMSE
axes[0].barh(importance_df["Variable"], importance_df["%IncMSE"], color="skyblue")
axes[0].set_xlabel("%IncMSE")
axes[0].set_title("Importance des variables - %IncMSE")

# IncNodePurity
axes[1].barh(importance_df["Variable"], importance_df["IncNodePurity"], color="orange")
axes[1].set_xlabel("IncNodePurity")
axes[1].set_title("Importance des variables - IncNodePurity")

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
plt.show()